name: Main Branch Server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev-interviewer-server
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy to Vercel"
        run: 
          npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.SERVER_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.SERVER_ORG_ID }}
