name: Dev Interviewer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev-interviewer-server
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Open Web Client Directory
        run: |
           ls -la
      - name: Install server dependencies
        run: npm ci
      - name: Server lint
        run: npm run lint
      - name: Build server
        run: npm run build --if-present
