name: Main Branch Server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev-interviewer-server
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install server dependencies
        run: npm ci
      - name: Build server
        run: npm run build --if-present
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.SERVER_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.SERVER_PROJECT_ID}} #Required 
          working-directory: ./
